format = """
[░▒▓](#a3aed2)\
$os\
$username\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_state\
$git_metrics\
[](fg:#394260)\
$fill\
[](fg:#394260)\
$nodejs\
$rust\
$golang\
$php\
$aws\
$kubernetes\
$nix_shell\
$time\
[](fg:#394260)\
\n $character"""

[line_break]
disabled = true

[fill]
symbol = ' '

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"
format = '[ $symbol ]($style)'

[os.symbols]
Ubuntu = ""
Debian = "󰣚"
Macos = ""

[username]
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#a3aed2 fg:#090c0c"
format = '[$user ]($style)'
disabled = false
show_always = true

[character]
success_symbol = '[](bold #03e8fc)'

[time]
disabled = false
style = "fg:#769ff0 bg:#394260"
format = '[󱑀 $time]($style)'
use_12hr = true
time_format = '%e %h |%l:%M:%S %p'

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch(:$remote_branch) ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
modified = '*'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
disabled = false
format = '[+$added](fg:#54e2a6 bg:#394260)[/](fg:#769ff0 bg:#394260)[-$deleted](fg:#e36385 bg:#394260)'

[nodejs]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#394260)]($style)'

[rust]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#394260)]($style)'

[golang]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#394260)]($style)'

[aws]
style = "fg:#769ff0 bg:#394260"
symbol = ''
format = '[$symbol$profile]($style) '

[kubernetes]
disabled = false
format = '[$context]($style):$namespace'
[[kubernetes.contexts]]
context_pattern = "twist-preregulated"
context_alias = "preregulated"
style = "bold red"
[[kubernetes.contexts]]
context_pattern = "twist-sweeps"
context_alias = "sweeps"
style = "bold purple"
[[kubernetes.contexts]]
context_pattern = "twist-staging"
context_alias = "staging"
style = "bold yellow"
[[kubernetes.contexts]]
context_pattern = "twist-dev"
context_alias = "dev"
style = "bold yellow"
[[kubernetes.contexts]]
context_pattern = "docker-desktop"
context_alias = "local"
style = "bold green"

[nix_shell]
style = "fg:#769ff0 bg:#394260"
impure_msg = '[impure shell](fg:#e36385 bg:#394260)'
pure_msg = '[pure shell](fg:#54e2a6 bg:#394260)'
unknown_msg = '[unknown shell](fg:#f0d04a bg:#394260)'
format = '[via ☃️ $state( \($name\))]($style)'
